### ISSUE TITLE
Footer en lugar equivocado

### ISSUE THREAD

**Issue by Hanaede** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-JPradillo#1]
https://github.com/iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-JPradillo/blob/58a5dfb073a63797cf19271e8c79ef26b6b6b92f/index.html#L9

El footer está en un lugar equivocado. Para que sea válido semánticamente, debe ir en último lugar.

**Comment by JPradillo** [comment]
Lo he puesto ahí a propósito porque me gusta ser diferente. De todas maneras lo modificaré para tu gusto.

**Comment by Hanaede** [comment]
Genial, espero a que lo corrijas.
