### ISSUE TITLE
H1 duplicado

### ISSUE THREAD

**Issue by Hanaede** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-JPradillo#2]
https://github.com/iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-JPradillo/blob/58a5dfb073a63797cf19271e8c79ef26b6b6b92f/index.html#L12

Un HTML solo debe contener un único h1, por lo que se debería cambiar por otros h, como h2, h3....
@JPradillo

**Comment by JPradillo** [comment]
Vale muchas gracias, lo solucionaré en un segundo.

**Comment by Hanaede** [comment]
Genial quedo a la espera
